Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'

Send This File And An Explanation Of The Error To yigit.atay@vanderbilt.eduUncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
Uncaught exception
Traceback (most recent call last):
  File "src/sliders.py", line 228, in valuechange
    self.generateImage()
  File "src/sliders.py", line 215, in generateImage
    self.graphicLabel.setPixmap(pixmap)
AttributeError: 'Ui_MainWindow' object has no attribute 'graphicLabel'
