Loaded dependency [python3/3.7.14]: gcc/10.3.0-binutils-2.36.1
Loaded module: python3/3.7.14

Loading python3/3.7.14
  Loading requirement: gcc/10.3.0-binutils-2.36.1
Loaded module: cuda/10.2
Loaded module: cudnn/v8.3.2.44-prod-cuda-10.2
Loaded module: ffmpeg/4.2.2
2022-11-22 20:39:47.936772: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2022-11-22 20:39:47.937295: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:58:00.0 name: Tesla V100-PCIE-32GB computeCapability: 7.0
coreClock: 1.38GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 836.37GiB/s
2022-11-22 20:39:47.940597: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /appl/cudnn/v8.3.2.44-prod-cuda-10.2/lib:/appl/cuda/10.2/lib64:/appl/python/3.7.14/lib:/appl/gcc/10.3.0-binutils-2.36.1/lib64:/appl/gcc/10.3.0-binutils-2.36.1/lib:/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2022-11-22 20:39:47.940643: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2022-11-22 20:39:48.128008: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2022-11-22 20:39:48.185031: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2022-11-22 20:39:48.331950: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2022-11-22 20:39:48.394285: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2022-11-22 20:39:48.395889: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /appl/cudnn/v8.3.2.44-prod-cuda-10.2/lib:/appl/cuda/10.2/lib64:/appl/python/3.7.14/lib:/appl/gcc/10.3.0-binutils-2.36.1/lib64:/appl/gcc/10.3.0-binutils-2.36.1/lib:/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2022-11-22 20:39:48.395902: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-11-22 20:39:48.396203: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2022-11-22 20:39:48.426457: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2800000000 Hz
2022-11-22 20:39:48.426664: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xb014840 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-11-22 20:39:48.426674: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2022-11-22 20:39:48.427855: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-11-22 20:39:48.427867: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      
/zhome/a2/4/155672/.local/lib/python3.7/site-packages/torch/nn/functional.py:1960: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/zhome/a2/4/155672/.local/lib/python3.7/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "/zhome/a2/4/155672/Desktop/DeepLearning/SparseVAE-Cell-Images/src/train-convvsc.py", line 38, in <module>
    reload_model=not args.do_not_resume)
  File "/zhome/a2/4/155672/Desktop/DeepLearning/SparseVAE-Cell-Images/src/models/base_model.py", line 193, in run_training
    f'{images_path}/sample_{run_name}_{epoch}.png')
  File "/zhome/a2/4/155672/.local/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/zhome/a2/4/155672/.local/lib/python3.7/site-packages/torchvision/utils.py", line 160, in save_image
    im.save(fp, format=format)
  File "/zhome/a2/4/155672/.local/lib/python3.7/site-packages/PIL/Image.py", line 2350, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '../results/images/sample_ConvVSC_cell_1_150_200_0-001_10.png'
